[CI] Update admin database url on heroku, fix tests and cleanup properly
[CI CORE E2E WEB] Fix specs on CI

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,8 +15,8 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  deploy-preview:
-    name: 'Deploy to Preview'
+  deploy-staging:
+    name: 'Deploy to Staging'
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -24,16 +24,16 @@ jobs:
       deployments: write
     outputs:
       database-id: ${{ steps.create-db.outputs.branch_id }}
-      preview-url: ${{ steps.vercel-deploy.outputs.preview_url }}
+      staging-url: ${{ steps.vercel-deploy.outputs.staging_url }}
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
       - name: Install CLI deps
         run: npm install -g neonctl vercel@latest
       - name: Destroy previously missed database branches
         run: |
           neonctl branches list -o json \
-          | jq '.[].name | select(. | startswith("github-deploy-${{ github.ref_name }}"))' -c \
+          | jq '.[] | select(.primary != true) | select(.name | startswith("github-deploy-main")) | .id' -c \
           | xargs -I % neonctl branches delete %
       - name: Create database branch
         uses: neondatabase/create-branch-action@v4
@@ -42,22 +42,23 @@ jobs:
           api_key: ${{ secrets.NEON_API_KEY }}
           branch_name: github-deploy-${{ github.ref_name }}-${{ github.run_id}}-${{ github.run_attempt }}
           database: books-about-food-prod
+          parent: main
         id: create-db
-      - name: Deploy preview to Vercel
+      - name: Deploy staging to Vercel
         id: vercel-deploy
         env:
           VERCEL_ORG_ID: ${{ secrets.BAF_VERCEL_ORG_ID }}
           VERCEL_PROJECT_ID: ${{ secrets.BAF_VERCEL_PROJECT_ID }}
         run: |
-          db_url=$(neonctl cs ${{ steps.create-db.outputs.branch_id }} --database-name books-about-food-prod --prisma --pooled)
-          direct_db_url=$(neonctl cs ${{ steps.create-db.outputs.branch_id }} --database-name books-about-food-prod --prisma)
+          db_url="$(neonctl cs ${{ steps.create-db.outputs.branch_id }} --database-name books-about-food-prod --prisma --pooled)"
+          direct_db_url="$(neonctl cs ${{ steps.create-db.outputs.branch_id }} --database-name books-about-food-prod --prisma)"
 
-          preview_url=$(vercel \
+          staging_url=$(vercel \
             --token=${{ secrets.VERCEL_DEPLOY_TOKEN }} \
             --scope=radical-innovation \
             --meta githubCommitAuthorName=${{ github.actor }} \
             --meta githubCommitAuthorLogin=${{ github.actor }} \
-            --meta githubCommitMessage="${{ github.event.head_commit.message }}" \
+            --meta githubCommitMessage="${{github.event.head_commit.message}}" \
             --meta githubCommitOrg=${{ github.repository_owner }} \
             --meta githubCommitRepo=books-about-food \
             --meta githubCommitRef=${{ github.ref_name }} \
@@ -73,13 +74,15 @@ jobs:
             --skip-domain \
           )
 
-          if [ -z "$preview_url" ]
+          if [ -z "$staging_url" ]
           then
-            echo "Preview URL not found"
+            echo "Staging URL not found"
             exit 1
           else
-            echo "preview_url=$preview_url" >> $GITHUB_OUTPUT
-            vercel alias $preview_url \
+            echo "staging_url=$staging_url" >> $GITHUB_OUTPUT
+            echo "$db_url"
+            echo $GITHUB_OUTPUT
+            vercel alias $staging_url \
               books-about-food-git-${{ github.ref_name }}.vercel.app \
               --scope=radical-innovation \
               --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
@@ -87,12 +90,12 @@ jobs:
 
   test:
     name: 'Run E2E tests'
-    needs: [deploy-preview]
+    needs: [deploy-staging]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
+        uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
         with:
           node-version: 20
       - name: Install dependencies and get database url
@@ -100,8 +103,10 @@ jobs:
         run: |
           npm -w packages/e2e ci
           npm i -g neonctl
-          echo "database-url=$(neonctl cs ${{ needs.deploy-preview.outputs.database-id }} --database-name books-about-food-prod --prisma --pooled)" >> $GITHUB_OUTPUT
-          echo "database-direct-url=$(neonctl cs ${{ needs.deploy-preview.outputs.database-id }} --database-name books-about-food-prod --prisma)" >> $GITHUB_OUTPUT
+
+          echo "database-url=$(neonctl cs ${{ needs.deploy-staging.outputs.database-id }} --database-name books-about-food-prod --prisma --pooled)" >> $GITHUB_OUTPUT
+          echo "database-direct-url=$(neonctl cs ${{ needs.deploy-staging.outputs.database-id }} --database-name books-about-food-prod --prisma)" >> $GITHUB_OUTPUT
+
         env:
           PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
       - name: Get installed Playwright version
@@ -129,7 +134,7 @@ jobs:
       - name: Run Playwright tests
         run: npx -w packages/e2e playwright test
         env:
-          DEPLOYMENT_URL: ${{ needs.deploy-preview.outputs.preview-url }}
+          DEPLOYMENT_URL: ${{ needs.deploy-staging.outputs.staging-url }}
           DATABASE_URL: ${{ steps.install-deps.outputs.database-url }}
           DATABASE_DIRECT_URL: ${{ steps.install-deps.outputs.database-direct-url }}
           NEXTAUTH_SECRET: ${{ secrets.AUTH_SECRET }}
@@ -142,7 +147,7 @@ jobs:
 
   deploy-prod:
     name: 'Deploy to Production'
-    needs: [deploy-preview, test]
+    needs: [deploy-staging, test]
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/main'
     env:
@@ -150,16 +155,50 @@ jobs:
       VERCEL_PROJECT_ID: ${{ secrets.BAF_VERCEL_PROJECT_ID }}
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
+        uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
         with:
           node-version: 20
+      - name: Install CLI deps
+        run: npm install -g neonctl vercel@latest
       - name: Promote Vercel deployment
         id: vercel-deploy
         run: |
-          primary_db=$(neonctl branches list -o json | jq '.[] | select(.primary) | .id' -r)
-          vercel promote ${{ needs.deploy-preview.outputs.preview-url }}  \
+          vercel promote ${{ needs.deploy-staging.outputs.staging-url }}  \
             --token=${{ secrets.VERCEL_DEPLOY_TOKEN }} \
             --scope=radical-innovation
-          neonctl branches set-primary ${{ needs.deploy-preview.outputs.database-id }}
-          neonctl branches delete $primary_db
+
+          neonctl branches set-primary ${{ needs.deploy-staging.outputs.database-id }}
+      - name: Update Admin Database URL
+        env:
+          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
+        run: |
+          db_url="$(neonctl cs ${{ needs.deploy-staging.outputs.database-id }} --database-name books-about-food-prod --prisma --pooled)"
+          direct_db_url="$(neonctl cs ${{ needs.deploy-staging.outputs.database-id }} --database-name books-about-food-prod --prisma)"
+
+          heroku config:set -a books-about-food-admin DATABASE_URL=$db_url DATABASE_DIRECT_URL=$direct_db_url
+
+  cleanup:
+    name: 'Clean Up'
+    needs: [deploy-staging, test, deploy-prod]
+    runs-on: ubuntu-latest
+    if: ${{ always() && github.run_attempt == 1 && github.ref == 'refs/heads/main' }}
+    env:
+      VERCEL_ORG_ID: ${{ secrets.BAF_VERCEL_ORG_ID }}
+      VERCEL_PROJECT_ID: ${{ secrets.BAF_VERCEL_PROJECT_ID }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+      - name: Install CLI deps
+        run: npm install --global vercel@latest neonctl
+      - name: Remove staging deployment
+        if: '${{ cancelled() || failure() }}'
+        run: vercel rm ${{ needs.deploy-staging.outputs.staging-url }} --token=${{ secrets.VERCEL_DEPLOY_TOKEN }} --scope=radical-innovation --yes || true
+      - name: Remove unused database branches
+        run: |
+          neonctl branches list -o json \
+          | jq '.[] | select(.primary != true) | select(.name | startswith("github-deploy-main")) | .id' -c \
+          | xargs -I % neonctl branches delete %
